### ISSUE TITLE
Add support for JSX

### ISSUE THREAD

**Issue by RobKohr** [anteprimorac/vscode-html-end-tag-labels#101]
**Describe the bug**
Tested in a js file with jsx code in it, and doesn't show labels on end tags
![image](https://user-images.githubusercontent.com/26756/83890384-b6232900-a719-11ea-80e5-f477b3345670.png)

**To Reproduce**
1. Open up a react project
2. Go to a component with html in it
3. Observe no tags

**Expected behavior**
Tags to show up.  Though I understand if JSX was not the target of this extension. Wasn't sure if I should put this as a bug or feature request.

**Comment by anteprimorac** [comment]
@RobKohr this is not something that was intended to support from the beginning, and it won't work out-of-the-box as it does for vue templates. But, I would like to have support for JSX.
