### ISSUE TITLE
Decorations are overridden

### ISSUE THREAD

**Issue by anteprimorac** [anteprimorac/vscode-html-end-tag-labels#16]
**Describe the bug**
Currently, this extension overrides other decorations added to vscode like gitlens.

**To Reproduce**
1. Install any other extension that adds decorations
2. Open any file where you expect decorations on the same line
3. See error

**Expected behavior**
It should prepend the decoration.

**Desktop (please complete the following information):**
 - OS: MacOS
 - VSCode Version 1.40.2
 - Extension Version 0.2.0

**Comment by ctf0** [comment]
this is expected because both decorates the same line

**Comment by anteprimorac** [comment]
@ctf0 yes, but we can update existing decoration by prepending our text and updating its style. I want to test this with other popular extensions that add decorations to see if this is a viable solution. I will update this issue with a list of extensions to check. Unfortunately, those tests can't be automatized because vscode doesn't expose decorations api in the test suit.

**Comment by anteprimorac** [comment]
Seems like currently, we won't be able to fix this because of https://github.com/microsoft/vscode/issues/33852.
