### ISSUE TITLE
Publish to Open VSX Registry

### ISSUE THREAD

**Issue by mountainash** [anteprimorac/vscode-html-end-tag-labels#183]
Could this extension please be published to https://open-vsx.org/ swell as Microsofts Visual Studio Marketplace? (for [easy] use in [VScodium](https://github.com/VSCodium/vscodium)

**Comment by anteprimorac** [comment]
@mountainash here it is https://open-vsx.org/extension/anteprimorac/html-end-tag-labels

**Comment by mountainash** [comment]
Wow - so fast, and working perfectly. Thank you a million times. You couldn't pay for better support!
