### ISSUE TITLE
Allow themes to define label color

### ISSUE THREAD

**Issue by entozoon** [anteprimorac/vscode-html-end-tag-labels#196]
**Describe the bug**
Can't target this plugin specifically when setting the colour.

**To Reproduce**
Workspace settings along the lines of 
```json
{
  "settings": {
    "workbench.colorCustomizations": {
      "htmlEndTagLabels.labelColor": "#ff0000"
    }
  }
}
```

**Expected behavior**
The way I understand the readme is that this would set the colour, but it doesn't appear to do anything. However 
```json
...
      "editorCodeLens.foreground": "#0000ff"
```
Does set the colour. Not ideal though, as it'll presumably also set the colour of other undesired things.

**Comment by anteprimorac** [comment]
@entozoon it has to be in the root of the `settings.json` file, like this:
```js
{
  // ... other settings
  "htmlEndTagLabels.labelColor": "#fff"
}
```

Also, the alternative is to use VSCode settings GUI

<img width="1447" alt="Screenshot 2021-03-26 at 14 35 38" src="https://user-images.githubusercontent.com/972083/112639877-0ef6b600-8e41-11eb-838d-0e30a9202c28.png">

**Comment by entozoon** [comment]
Ah, so you can't customise the colour with a [theme](https://code.visualstudio.com/docs/getstarted/themes)?
That's a shame. You can [see what I tried](https://github.com/entozoon/vscode-myketheme/blob/master/themes/myketheme.json#L414)

**Comment by anteprimorac** [comment]
@entozoon, this is definitely something that we could implement. Are you interested in implementing this?

**Comment by entozoon** [comment]
Interested, yes. Probably won't find the time but I'll make a note

**Comment by anteprimorac** [comment]
@entozoon, that's fine, thank you. Please, just let me know if you start working on this.

**Comment by entozoon** [comment]
Stale, perhaps. Completed? No
