### ISSUE TITLE
Add javascript parser

### ISSUE THREAD

**Issue by sksundram** [anteprimorac/vscode-html-end-tag-labels#198]
**Describe the bug**
This extension should not be working on JavaScript files. I wrote a simple for loop and it displays right below it.

**To Reproduce**
This is the for loop that I wrote.
```js
for (let i = 0; i < colors.length; i++) {
  console.log(colors[i]);
}
/.length
```

**Expected behavior**
The `/.length` should not be displayed in JavaScript files.

**Screenshots**
![vscode_htmlExtension_js_bug](https://user-images.githubusercontent.com/10360265/107007415-851f5a80-67b8-11eb-9218-ee1e32f18ef0.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - VSCode Version: 1.53.0
 - Extension Version: 0.6.0

**Comment by mrmikeshields** [comment]
I'm getting the same. The extension seems to be kicking in when it sees a '<'. Possibly interpreting it as the start of a html tag.

**Comment by anteprimorac** [comment]
Thank you for reporting this issue. I will disable the extension in js files because initially it was added because of JSX support, but currently, we only have an HTML parser and parsing JS code with an HTML parser won't give us desired result.

**Comment by simonhermann** [comment]
any update on this?

**Comment by iDad5** [comment]
Hi, I have the same issue with .ty Typescript Files - which are similar to js files mostly...

**Comment by anteprimorac** [comment]
@sksundram @mike-shields-dev @iDad5, I've introduced basic support for JSX and React. Please, try it and let me know how it feels.
