### ISSUE TITLE
Show the Label only on active row

### ISSUE THREAD

**Issue by grafst** [anteprimorac/vscode-html-end-tag-labels#216]
First: Great Plugin the best I could find so far for this use case

**Problem**
I'm  a bit destracted by the many labels

**Solution I would appreciate**
A Setting which allows to:
Only show the label for the active row (where the curser is at) and hide all the others. 
(Maybe Even a command to toggle between _all_, _none_ and _current_)

**Considered Alternatives**
Disable and enable the extension on demand (tedious)

I would be willing to help In any way possible but I don't know Javascript... :(

**Comment by anteprimorac** [comment]
@grafst, thank you for this suggestion, but have you tried changing the color of labels with the `htmlEndTagLabels.labelColor` setting? I have found for myself that using dark color helps in reducing the feeling of cluterness.

**Comment by grafst** [comment]
ok, I will try.
another way to reduce clutter would be to only use classes when there is no id.

**Comment by anteprimorac** [comment]
@grafst it should already work like that.

**Comment by grafst** [comment]
I believe I saw it using both. I can take a screenshot later.
