### ISSUE TITLE
Effect is applied on text similar to html tags

### ISSUE THREAD

**Issue by RyanNorooz** [anteprimorac/vscode-html-end-tag-labels#310]
### **the bug:**
the `end tag label` effect is being applied on non html files too
if files like package.json have any content that are similar to html tags, the `end tag label` will be corruptly visible around that area

i.e.: **package.json**
<img alt="package.json" src="https://user-images.githubusercontent.com/58340667/139782183-e2ecd8bd-4807-4683-bddc-eb78d34c0482.png" width="500">

### **Expected behavior:**
the effect should only be applied on html tags

### **Additional context**
<details>
<summary>click to see</summary>

#### **environment:**
 - OS: windows 10
 - VSCode Version: [1.61.2]
 - Extension Version: [0.8.0]

</details>

### **Update:**
apparently other languages also have this problem: 
twig: https://github.com/anteprimorac/vscode-html-end-tag-labels/issues/279
javascript: https://github.com/anteprimorac/vscode-html-end-tag-labels/issues/198
php: https://github.com/anteprimorac/vscode-html-end-tag-labels/issues/271

**Comment by anteprimorac** [comment]
@RyanNorooz, thank you for the bug report. Currently, I am working on this. I can't tell when I will finish the work because we have to solve this per language.

**Comment by anteprimorac** [comment]
I will create an issue per each language that this extension supports.
