### ISSUE TITLE
Too many classes are shown

### ISSUE THREAD

**Issue by RyanNorooz** [anteprimorac/vscode-html-end-tag-labels#311]
**Is your feature request related to a problem? Please describe.**
when using ui libraries like [tailwindcss](https://tailwindcss.com), its common to have 10 or more classes on some html elements
the `end tag label` is showing all the css classes at the end of the tag and this is really ugly

**Describe the solution you'd like**
an option to limit the number of classes shown would be really great
or an option to disable css classes altogether and only show html ids

**Describe alternatives you've considered**
meditation, green tea, traveling

**Additional context**
![image](https://user-images.githubusercontent.com/58340667/139784654-30aaa3d1-48f9-4ad4-9989-361476e504cb.png)

**Comment by anteprimorac** [comment]
@RyanNorooz, thank you for your feature request. I was trying to come out with a universal solution for this issue, but I couldn't, so I agree with you that adding a configuration for this would be the best solution. Would you like to work on this?

**Comment by ranapartap** [comment]
Yep just show ID of tag or first classname if ID is not available. Also make some lighter the extension, sometimes its just processing... processing and processing no class is showing.

**Comment by anteprimorac** [comment]
I am closing this because I don't encounter this problem or know an elegant solution. If someone knows how to solve this, please open a new enhancement request or create a PR.
