### ISSUE TITLE
Add blade parser

### ISSUE THREAD

**Issue by patrickmaciel** [anteprimorac/vscode-html-end-tag-labels#336]
![image](https://user-images.githubusercontent.com/671670/151017823-a9c1a444-0169-4f7e-aa8d-755b65de6800.png)

This is a Laravel component named `<x-input.container>` and the extension named as `container` only.

**Comment by anteprimorac** [comment]
@patrickmaciel, thank you for reporting. To fix this, we will have to implement actual support for blade templates because currently, we are using an HTML language service to parse files.
