### ISSUE TITLE
Language / file extension exclude option

### ISSUE THREAD

**Issue by palansher** [anteprimorac/vscode-html-end-tag-labels#402]
Your really useful extension adds end tags even to lines in JavaScript files. That, obviously ... bad.

My app.js file (contains only JS code):
![image](https://user-images.githubusercontent.com/24850253/185804875-a5f1749e-9166-452b-80c2-3767bd92c508.png)

Would you please implement some possibility to choose which language/ file extension to choose or to exclude for end tags functionality.

Thanks!!!!

**Comment by anteprimorac** [comment]
@palansher, thank you for the bug report. This should be fixed in the new `v0.10.0` version.
