### ISSUE TITLE
Suggestion: option to put labels inside tag.

### ISSUE THREAD

**Issue by BevansDesign** [anteprimorac/vscode-html-end-tag-labels#441]
First, this is a really helpful extension, and thanks for making it.

Right now the extension shows labels like this:
`</div>/#main.container`

My suggestion: it'd be great to have it display like this, or give this option:
`</div#main.container>`

I think that would make it a little easier to read code when dealing with multiple nested elements.

Current example:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/296937/201989800-626f7730-b916-4834-bf6f-1fe50152cd4d.png">
Suggested:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/296937/201989954-a84d43c8-88a1-4568-8553-34614971ed90.png">
<img width="359" alt="image" src="https://user-images.githubusercontent.com/296937/201990499-35b9caa9-a477-4476-a1f7-498f5b7f63f0.png">

Just a thought. Keep up the great work!

**Comment by akinuri** [comment]
While I agree that the `</div>/#main.container` isn't ideal, I don't think `</div#main.container>` is that better. I don't think the labels should be a part of the end tag, but an extension of it.

Instead, there should be some option to let the user decide for the format.  For example, the current format can be represented like this:

```
template: "/{element_signature}", // </div>/#main.container
```

This way, one can modify the labels to one's liking. Personally, the first thing I'll do is to get rid of the `/` and add a space.

```
template: " {element_signature}", // </div> #main.container
```

I was just about to open an issue about this. Hope this gets solved.

**Comment by akinuri** [comment]
For the time being, I decided to modify the extension. Made the following change in the [closing-labels-decorations.ts:165](https://github.com/anteprimorac/vscode-html-end-tag-labels/blob/495a68981f819b8136111cdc0e35e2bb83d04281/src/closing-labels-decorations.ts#L165) to get rid of the `/` and add a space.

```
renderOptions: { after: { contentText: ` ${label}` } },
```

Had to disable and enable again to see the change.

**Comment by anteprimorac** [comment]
Thank you
