### ISSUE TITLE
[feature] make label coloring configurable instead of fixed

### ISSUE THREAD

**Issue by ctf0** [anteprimorac/vscode-html-end-tag-labels#45]
atm the color is fixed 
https://github.com/anteprimorac/vscode-html-end-tag-labels/blob/b8de3173aeacbf6f0bd9bcecf1fc6890a873027c/src/closing-labels-decorations.ts#L14

however having a away to configure that would be very helpful.

**Comment by anteprimorac** [comment]
@ctf0 thank you for the issue. Yes, it's already configurable, but still, I think it would be better to create a new settings option that would give users the ability to have two different colors for this extension decorations and code lens.

**Comment by ctf0** [comment]
i can make a PR if u want

**Comment by anteprimorac** [comment]
@ctf0 if you have time, go for it.

**Comment by ctf0** [comment]
ok, np
