### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by K2adir** [anteprimorac/vscode-html-end-tag-labels#452]
This plugin is wonderful, and thank you very much for making it.

My question/suggestion is,

sometimes, it works fine with my JSX files, and sometimes it doesn't.

How could I make it work with all of my JSX files?

**Comment by anteprimorac** [comment]
@K2adir, thank you for the bug report. I've introduced basic support for JSX and React in the new `v0.10.0` version. Please, try it and let me know how it feels.

**Comment by CzarOfScripts** [comment]
It doesn't work with `MUI` components, for example: 
```javascript 
<Box className="test"></Box>
```

**Comment by anteprimorac** [comment]
@CzarOfScripts, this should work in the latest version.

**Comment by K2adir** [comment]
> @K2adir, thank you for the bug report. I've introduced basic support for JSX and React in the new `v0.10.0` version. Please, try it and let me know how it feels.

Thank you! Now it works regardless of the setup. Thank you so much

**Comment by CzarOfScripts** [comment]
> @CzarOfScripts, this should work in the latest version.

Yes, everything works great! Thank you!
