### ISSUE TITLE
✨ Add SCSS support

### ISSUE THREAD

**Issue by jd-solanki** [anteprimorac/vscode-html-end-tag-labels#473]
**Is your feature request related to a problem? Please describe.**
Hi, I really love this extension ❤️ 

It gives me an overview of where I am. THe problem this extension solves also exist in SCSS where we use nesting, We get completely lost on which selector we are 🙄 

**Describe the solution you'd like**
SCSS support just like HTML tags

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by anteprimorac** [comment]
@jd-solanki, thank you for the suggestion. I will have to get back to you after researching SCSS and how this feature fits into this extension.

**Comment by anteprimorac** [comment]
This doesn't fit into this extension because this extension is mainly focused on HTML written in different languages. Please let me know if you have a good case for adding this to the extension.
