### ISSUE TITLE
✨ Only show when hovering over end tag

### ISSUE THREAD

**Issue by jd-solanki** [anteprimorac/vscode-html-end-tag-labels#530]
**Is your feature request related to a problem? Please describe.**
Hi 👋🏻 

Thanks for making this awesome extension. I noticed  using this extension with code format like below makes code very hard to read:
<img width="486" alt="image" src="https://github.com/anteprimorac/vscode-html-end-tag-labels/assets/47495003/0efa70dd-fc22-4833-a9e9-5e2002097388">

**Describe the solution you'd like**
Option to only show labels on hover of ending tag

**Describe alternatives you've considered**
N/A

**Additional context**
Thanks ❤️

**Comment by anteprimorac** [comment]
Hiding it behind the hover is against this extension's main point: quickly finding out where the end tag of the element you are looking for is.
