### ISSUE TITLE
Add support for CSS modules

### ISSUE THREAD

**Issue by trlanfeng** [anteprimorac/vscode-html-end-tag-labels#554]
I hope to add support for CSS Modules. Currently, the className attribute only supports string display, but does not support CSS Modules.

Thanks.

![CSS Modules](https://img1.imgtp.com/2023/07/25/6kumiACG.png "CSS Modules")

**Comment by anteprimorac** [comment]
I am not using CSS modules; could you let me know how you think this would work with it?
