### ISSUE TITLE
Add support for PHP and Twig

### ISSUE THREAD

**Issue by Elvanos** [anteprimorac/vscode-html-end-tag-labels#62]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Trigger the extension automatically on opening a PHP or Twig file.

**Describe alternatives you've considered**
Opening a HTML file BEFORE opening PHP or Twig files - works, but rather inconvenient.

**Additional context**
Not much, just add PHP and Twig languages to the `package.json` trigger list.

**Comment by anteprimorac** [comment]
@elvanos thank you for submitting this feature request

**Comment by Elvanos** [comment]
@anteprimorac thanks for the quick reply! This is very, very easy to add, I already did it on my end with a tiny tweak to the package.json file.

```
	"activationEvents": [
		"onLanguage:html",
		"onLanguage:php",
		"onLanguage:twig",
		"onLanguage:blade",
		"onLanguage:vue-html"
	],
```

**Comment by anteprimorac** [comment]
@elvanos can you submit that as Pull Request?

**Comment by Elvanos** [comment]
@anteprimorac Done.

**Comment by anteprimorac** [comment]
Added with #63 and #74
