### ISSUE TITLE
double slashes?

### ISSUE THREAD

**Issue by goyalyashpal** [anteprimorac/vscode-html-end-tag-labels#654]
hi! thanks a lot for such a wonderful extension.

* the currently used label prefix is single forward slash `/`
* but html documents often become dense, and at those times, this becomes hard to separate out from the closing slash
* so, though this can easily be customized, but just thought to ask if it makes sense to make it to `//` by default.

thanks again.

https://github.com/anteprimorac/vscode-html-end-tag-labels/blob/b65013537f078fdfc9f312d57831ea188dd0ff24/README.md?plain=1#L27

<img src="https://github.com/anteprimorac/vscode-html-end-tag-labels/assets/19423063/e52359f4-d30f-423c-8f06-6087b3724f9f" width=600px />

**Comment by anteprimorac** [comment]
Thank you for submitting this request. I've added the ability to customize this because it's hard to please everyone's taste. Personally, I prefer the single slash `/` because before this extension, my team used to use HTML comments `<!-- /.class -->` as end tag labels.

**Comment by goyalyashpal** [comment]
> the single slash `/` because before this extension, my team used to use HTML comments `<!-- /.class -->` as end tag labels.

hehe right. i learnt similar in C by:

```c
} /* END main */
```

anyhow, the single one makes sense in comment format as theres good amount of separation with `<!-- `. but here, thats not the case.

thanks for letting me know regardless 😃 , have a nice time.
