### ISSUE TITLE
Custom attribute support for XML files

### ISSUE THREAD

**Issue by ShinaZin** [anteprimorac/vscode-html-end-tag-labels#669]
This feature would be useful for XML files (not just HTML). For example, I have the following file:
```xml
<container name="settings" id="f866700f-befe-4ead-9894-56de9141401c">
   <list name="keys" id="fb8e2a86-41b7-4b47-8b66-29142f80a175">
   <!-- ... -->
   </list>
</container>
```

Currently the extension will display `/#f866700f-befe-4ead-9894-56de9141401c` for `container` and `/#fb8e2a86-41b7-4b47-8b66-29142f80a175` for `list`. I think a `name` attribute value would be more useful instead of `id` (in this example).
Maybe we can implement a setting that allows us to specify a custom attribute (or list of attributes) to be used as a label?
If this setting is enabled, the default behavior should be disabled.

**Resulting example** (custom attribute set to `name`):
```xml
<container name="settings" id="f866700f-befe-4ead-9894-56de9141401c">
   <list name="keys" id="fb8e2a86-41b7-4b47-8b66-29142f80a175">
   <!-- ... -->
   </list> /keys
</container> /settings
```

**Comment by anteprimorac** [comment]
Thank you for submitting the request, but this extension is focused only on HTML, so I am not interested in supporting XML and maintaining that feature.
