### ISSUE TITLE
The extension does not activate when language mode is Django HTML in HTML files

### ISSUE THREAD

**Issue by ahmedsaoudi** [anteprimorac/vscode-html-end-tag-labels#707]
**Describe the bug**
In `.html` pages, the extension doesn't activate automatically when the language mode is set to Django HTML. 

**To Reproduce**
1. Open command palette and type "Change language mode" 
2. Choose "Django HTML" 
3. Open an `.html` file prepopulated with HTML code
4. HTML end-tag labels aren't visible. 

**Expected behavior**
HTML end-tag labels visible when opening an HTML file. 

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - VSCode Version: 1.87
 - Extension Version: 1.0.0

**Additional context**
-

**Comment by anteprimorac** [comment]
@ahmedsaoudi thank you for reporting the issue, but I do not use django and do not want to introduce additional features that I can’t maintain.
